# Main Import Statements
This part creates the basic import functions

eval "$(~/miniconda3/bin/conda shell.bash hook)"

In [1]:
import os
import pandas as pd
pd.set_option('max_colwidth', None)
pd.set_option('display.precision', 4)

In [2]:
def get_data_file_path(current_trial_name="v5_eval", base_folder="game_logs", trial_base_name="alfworld_eval_", csv_file_name="alfworld_results.csv"):
    """returns the csv file path."""
    current_trial_folder = trial_base_name + current_trial_name
    file_path = os.path.join(base_folder, current_trial_folder, csv_file_name)
    return file_path

In [3]:
def convert_string_to_bool(in_string):
    """if string ="" False, else True"""
    if in_string:
        return True
    else:
        return False

def convert_string_to_bool_int(in_string):
    """if string ="" False, else True"""
    if in_string:
        return 1
    else:
        return 0

def convert_bool_string_to_bool_int(in_string):
    """ if string==False -> False, etc."""
    if in_string=="(False,)" or in_string=="False":
        return 0
    elif in_string=="(True,)" or in_string=="True":
        return 1
    elif in_string=="0":
        return 0
    elif in_string=="1":
        return 1
    else:
        print(type(in_string))
        print(in_string)
        print(in_string[0])
        raise Exception("Error in Transforming BoolString to Int")

# Analysis
This is the new part of the analysis.

In [4]:
def load_data(trial_name):
    file_path=os.path.join("game_logs",f"alfworld_eval_{trial_name}","alfworld_results.csv")
    df = pd.read_csv(
        file_path, 
        quoting=1,
        index_col=False, 
        converters = {
            "early_stop":convert_string_to_bool_int, 
            "error": convert_string_to_bool_int
        }
    )
    return df

In [5]:
# Analysis Part Three
def analyse_data_basic(input_data):
    # This is the table that shows total results.
    out = input_data.groupby(["model","keys_removed"]).sum().reset_index()
    out["total"] = input_data.groupby(["model","keys_removed"])["success"].count().reset_index()["success"]
    
    # out_header_order = ["model", "prompt_name","env_idx","env_type","success","done","early_stop","num_of_steps","num_nothing_happens","num_repetitions","num_no_json","error"]
    out_header_order = ["model", "keys_removed","env_idx","success","done","early_stop","error","num_of_steps"]

    out = out[out_header_order]
   
    # out["normalised_nothing"] = out["num_nothing_happens"] / out["num_of_steps"]
    # out["normalised_reps"] = out["num_repetitions"] / out["num_of_steps"]
    # out["normalised_nothing"] = out["total_nothing"] / out["num_of_steps"]
    # out["normalised_not_valid_nothing"] = out["total_not_valid_nothing"] / out["num_of_steps"]
    # out["proportion_of_not_valid_in_nothing"] = out["total_not_valid_nothing"] / out["total_nothing"]
    # out["proportion_of_valid_in_nothing"] = out["total_valid_nothing"] / out["total_nothing"]
    # out["proportion_of_hallucinated_in_not_valid"] = out["hallucinated_not_valid_nothing"] / out["total_not_valid_nothing"]
    # out["proportion_of_fake_in_not_valid"] = out["fake_not_h_not_valid_nothing"] / out["total_not_valid_nothing"]
    
    out["success_percentage"] = out["success"] / 135 * 100   # out["success_percentage_done"] = out["success"] / out["done"]
    # out["done_percentage"] = out["done"] / out["total"]
    x = out.groupby("keys_removed")

    out_header_order = ["keys_removed","model","success_percentage","done"]
    out2 = out[out_header_order]
    return x, out2

def analyse_data_old(input_data):
    # This is the table that shows total results.
    out = input_data.groupby(["model","prompt_name","correction"]).sum().reset_index()
    out["total"] = input_data.groupby(["model","prompt_name","correction"])["success"].count().reset_index()["success"]
    
    # out_header_order = ["model", "prompt_name","env_idx","env_type","success","done","early_stop","num_of_steps","num_nothing_happens","num_repetitions","num_no_json","error"]
    out_header_order = ["model", "prompt_name","correction","env_idx","success","done","early_stop","error","num_of_steps"]

    out = out[out_header_order]
   
    # out["normalised_nothing"] = out["num_nothing_happens"] / out["num_of_steps"]
    # out["normalised_reps"] = out["num_repetitions"] / out["num_of_steps"]
    # out["normalised_nothing"] = out["total_nothing"] / out["num_of_steps"]
    # out["normalised_not_valid_nothing"] = out["total_not_valid_nothing"] / out["num_of_steps"]
    # out["proportion_of_not_valid_in_nothing"] = out["total_not_valid_nothing"] / out["total_nothing"]
    # out["proportion_of_valid_in_nothing"] = out["total_valid_nothing"] / out["total_nothing"]
    # out["proportion_of_hallucinated_in_not_valid"] = out["hallucinated_not_valid_nothing"] / out["total_not_valid_nothing"]
    # out["proportion_of_fake_in_not_valid"] = out["fake_not_h_not_valid_nothing"] / out["total_not_valid_nothing"]
    
    out["success_percentage"] = out["success"] / 135 * 100
    # out["success_percentage_done"] = out["success"] / out["done"]
    # out["done_percentage"] = out["done"] / out["total"]
    x = out.groupby("prompt_name")

    out_header_order = ["prompt_name","model","success_percentage","done"]
    out2 = out[out_header_order]
    return x, out2

def analyse_data_new(input_data):
    # This is the table that shows total results.
    out = input_data.groupby(["model","prompt_name","correction","resample"]).sum().reset_index()
    out["total"] = input_data.groupby(["model","prompt_name","correction","resample"])["success"].count().reset_index()["success"]
    
    # out_header_order = ["model", "prompt_name","env_idx","env_type","success","done","early_stop","num_of_steps","num_nothing_happens","num_repetitions","num_no_json","error"]
    out_header_order = ["model", "prompt_name","correction","resample","env_idx","success","done","early_stop","error","num_of_steps","num_nothing_happens","num_repetitions","num_no_command","total_in_token_accumulated","total_out_token_accumulated", "num_correction"]

    out = out[out_header_order]
    out["success_percentage"] = out["success"] / 135 * 100
    x = out.groupby("prompt_name")

    out_header_order = ["prompt_name","model","success_percentage","done"]#,"num_nothing_happens","num_repetitions","total_in_token_accumulated","total_out_token_accumulated", "num_correction"]
    out2 = out[out_header_order]
    return x, out2

def no_groupby_analyse_data(input_data):
    # This is the table that shows total results.
    out = input_data.groupby(["model","prompt_name","correction","resample"]).sum().reset_index()
    out["total"] = input_data.groupby(["model","prompt_name","correction","resample"])["success"].count().reset_index()["success"]
    
    # out_header_order = ["model", "prompt_name","env_idx","env_type","success","done","early_stop","num_of_steps","num_nothing_happens","num_repetitions","num_no_json","error"]
    out_header_order = ["model", "prompt_name","correction","resample","env_idx","success","done","early_stop","error","num_of_steps"]

    out = out[out_header_order]
    out["success_percentage"] = out["success"] / 135 * 100
    return out
    
def create_pivot(in_data,variable="success",aggregation_function="sum"):# pivot1 = out.pivot(index=["keys_removed"],columns=["env_type"], values=["success"])
    pivot_table = pd.pivot_table(in_data, index=["model","prompt_name"],columns=["env_type"], aggfunc={variable:aggregation_function})
    pivot_table.columns = pivot_table.columns.droplevel(0)
    # pivot1.columns.name=None
    piv_table = pivot_table.reset_index()
    return piv_table

In [16]:
# file_name = "v5_2_eval_main"
file_name = "v5_eval_correction"
# file_name = "v5_eval"
# file_name = "v5_3_eval"
# file_name = "v5_3_eval_16K"
# file_name = "v5_3_test"




# new_eval = load_data("v4_0_0_eval")
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_old(new_eval)
y.to_csv(f"{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')

x.head()

,model,prompt_name,correction,env_idx,success,done,early_stop,error,num_of_steps,success_percentage
0,Qwen/Qwen2.5-32B-Instruct,react-1_0,True,8911,19,36,98,0,6084,14.0741
1,Qwen/Qwen2.5-32B-Instruct,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,True,8911,15,33,101,0,4359,11.1111

In [258]:
file_name = "v4_1_0_eval"
# new_eval = load_data("v4_1_0_eval")
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')

x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,success_percentage
0,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+action,False,False,9045,55,76,59,0,2339,40.7407
1,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+current_location+locations_visited+current_inventory+thought+action,False,False,9045,24,40,95,0,1889,17.7778
2,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+plan+thought+action,False,False,9045,20,37,98,0,1957,14.8148
3,gpt-3.5-turbo-1106,jsonstate-1_0-k-locations_visited+current_location+current_inventory+action,False,False,9045,25,32,103,0,1372,18.5185
4,gpt-3.5-turbo-1106,jsonstate-1_0-k-plan+action,False,False,9045,37,56,79,0,2171,27.4074
5,gpt-3.5-turbo-1106,jsonstate-1_0-k-thought+action,False,False,9045,35,65,70,0,2742,25.9259
6,gpt-3.5-turbo-1106,stringstate-1_0-k-thought+action,False,False,9045,46,85,49,1,3834,34.0741

In [270]:
file_name = "v4_1_0_eval_correction"
# new_eval = load_data("v4_1_0_eval_correction")
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')

x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,success_percentage
0,gpt-3.5-turbo-1106,jsonreact-1_0-v1,True,False,9045,30,38,97,0,1739,22.2222
1,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+locations_visited+current_location+current_inventory+thought+action,True,False,9045,30,42,93,0,1640,22.2222
2,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+plan+thought+action,True,False,9045,36,49,86,0,1813,26.6667
3,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+thought+action,True,False,9045,57,69,66,0,1678,42.2222
4,gpt-3.5-turbo-1106,jsonstate-1_0-k-thought+action,True,False,9045,58,80,55,0,2117,42.9630
5,gpt-3.5-turbo-1106,react-1_0,True,False,9045,39,56,79,0,3695,28.8889

In [260]:
file_name = "v4_1_0_eval_resample"
# new_eval = load_data("v4_1_0_eval_resample")
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')

x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,success_percentage
0,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+current_inventory+current_location+thought+action,False,True,9045,26,94,41,0,7080,19.2593
1,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+current_location+current_inventory+thought+action,False,True,9045,33,95,40,0,6218,24.4444
2,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+locations_visited+current_location+current_inventory+thought+action,False,True,9045,29,86,49,0,6870,21.4815
3,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+thought+action,False,True,9045,49,104,31,0,5558,36.2963

In [261]:
file_name = "v4_1_0_eval_correction_resample"
# new_eval = load_data("v4_1_0_eval_correction_resample")
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')

x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,success_percentage
0,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+locations_visited+current_location+current_inventory+thought+action,True,True,9045,29,98,37,0,6881,21.4815

In [262]:
file_name = "v4_1_1_eval"
# new_eval = load_data("v4_1_1_eval")
new_eval = load_data(file_name)
# new_eval.head()

# y = no_groupby_analyse_data(new_eval)

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')

x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,success_percentage
0,gpt-3.5-turbo-0125,jsonstate-1_0-k-goal+current_location+current_inventory+thought+action,False,False,9045,59,106,29,0,3839,43.7037
1,gpt-3.5-turbo-0125,jsonstate-1_0-k-thought+action,False,False,9045,44,97,38,0,4457,32.5926
2,gpt-3.5-turbo-0125,react-1_0,False,False,9045,21,61,74,0,5687,15.5556
3,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+action,False,False,9045,66,100,35,0,3121,48.8889
4,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,False,False,9045,70,125,10,0,3931,51.8519
5,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+locations_visited+current_location+current_inventory+thought+action,False,False,9045,55,114,19,2,4133,40.7407
6,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+thought+action,False,False,9045,51,115,20,0,4381,37.7778
7,gpt-3.5-turbo-0125,stringstate-1_0-k-thought+action,False,False,9045,40,107,28,0,4800,29.6296
8,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+action,False,False,9045,60,96,39,0,3288,44.4444
9,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,False,False,9045,67,104,31,0,3104,49.6296
10,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+locations_visited+current_location+current_inventory+thought+action,False,False,9045,57,92,43,0,3114,42.2222
11,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+thought+action,False,False,9045,51,95,40,0,3518,37.7778

In [300]:
file_name = "v4_1_1_eval_correction"
# new_eval = load_data("v4_1_1_eval_correction")
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')

x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,num_nothing_happens,num_repetitions,total_in_token_accumulated,total_out_token_accumulated,num_correction,success_percentage
0,gpt-3.5-turbo-0125,jsonstate-1_0-k-goal+current_location+current_inventory+thought+action,True,False,9045,91,119,16,0,2729,650,125,10397123,184299,48,67.4074
1,gpt-3.5-turbo-0125,jsonstate-1_0-k-thought+action,True,False,9045,95,117,18,0,2743,715,131,7182638,110149,122,70.3704
2,gpt-3.5-turbo-0125,react-1_0,True,False,9045,53,79,56,0,4773,1536,424,10623807,143036,172,39.2593
3,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+action,True,False,9045,69,97,38,0,2947,1083,229,5752220,58247,4,51.1111
4,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,True,False,9045,89,125,10,0,3069,802,93,10207049,157104,46,65.9259
5,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+locations_visited+current_location+current_inventory+thought+action,True,False,9045,85,115,19,1,2917,893,115,12278377,258069,48,62.9630
6,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+thought+action,True,False,9045,89,121,14,0,3037,730,103,8341478,116836,125,65.9259
7,gpt-3.5-turbo-0125,stringstate-1_0-k-thought+action,True,False,9045,79,116,19,0,3257,1094,140,7962481,109383,212,58.5185

In [264]:
file_name = "v4_1_1_eval_resample"
# new_eval = load_data("v4_1_1_eval_resample")
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')

x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,success_percentage
0,gpt-3.5-turbo-0125,react-1_0,False,True,9045,30,112,23,0,8597,22.2222
1,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,False,True,9045,64,135,0,0,4501,47.4074
2,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+current_location+current_inventory+thought+action,False,True,9045,40,101,34,0,6259,29.6296
3,gpt-3.5-turbo-1106,react-1_0,False,True,9045,30,103,32,0,8732,22.2222
4,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,False,True,9045,61,126,9,0,4831,45.1852

In [303]:
file_name = "v4_1_1_eval_correction_resample"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,num_nothing_happens,num_repetitions,total_in_token_accumulated,total_out_token_accumulated,num_correction,success_percentage
0,gpt-3.5-turbo-0125,jsonstate-1_0-k-goal+current_location+current_inventory+thought+action,True,True,9045,94,130,5,0,3259,820,25,13069631,220012,53,69.6296
1,gpt-3.5-turbo-0125,react-1_0,True,True,9045,55,117,16,2,7160,2580,27,17886491,286485,174,40.7407
2,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,True,True,9045,95,131,4,0,3236,913,23,10517505,151078,59,70.3704
3,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+current_location+current_inventory+thought+action,True,True,9045,50,106,29,0,5146,2560,124,16718460,179695,34,37.0370
4,gpt-3.5-turbo-1106,react-1_0,True,True,9045,46,100,35,0,7682,2918,55,17584889,419937,319,34.0741
5,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,True,True,9045,96,131,4,0,3489,1369,15,10437758,142697,54,71.1111

In [10]:
file_name = "v4_1_2_eval"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,num_nothing_happens,num_repetitions,num_no_command,total_in_token_accumulated,total_out_token_accumulated,num_correction,success_percentage
0,gpt-3.5-turbo-0301,react-1_0,False,False,9045,70,123,1,11,5857,1223,7,5857,14131480,110180,0,51.8519
1,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+current_location+current_inventory+thought+action,False,False,9045,61,92,43,0,3133,1096,279,742,11939053,199145,0,45.1852
2,gpt-3.5-turbo-1106,jsonstate-1_0-k-thought+action,False,False,9045,56,102,33,0,3799,926,178,202,10647368,141161,0,41.4815
3,gpt-3.5-turbo-1106,react-1_0,False,False,9045,54,96,39,0,4629,1909,229,4629,10124475,90932,0,40.0000
4,gpt-3.5-turbo-1106,stringstate-1_0-k-action,False,False,9045,42,120,15,0,4843,2469,103,128,8393141,58467,0,31.1111
5,gpt-3.5-turbo-1106,stringstate-1_0-k-current_location+current_inventory+action,False,False,9045,58,116,19,0,4077,1624,196,243,9321620,96653,0,42.9630
6,gpt-3.5-turbo-1106,stringstate-1_0-k-current_location+current_inventory+thought+action,False,False,9045,58,114,21,0,4181,1430,148,350,12929287,181520,0,42.9630
7,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+action,False,False,9045,64,114,21,0,3867,1754,157,132,8283142,92681,0,47.4074
8,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+current_location+current_inventory+action,False,False,9045,85,113,22,0,3207,1050,131,211,8144276,104590,0,62.9630
9,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,False,False,9045,68,118,17,0,3909,1086,105,268,13654330,206856,0,50.3704
10,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+thought+action,False,False,9045,60,120,15,0,4211,1290,100,95,12435019,163789,0,44.4444
11,gpt-3.5-turbo-1106,stringstate-1_0-k-thought+action,False,False,9045,49,106,28,1,4365,1597,179,187,11216378,159796,0,36.2963

In [21]:
file_name = "v4_1_2_eval_correction"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,num_nothing_happens,num_repetitions,num_no_command,total_in_token_accumulated,total_out_token_accumulated,num_correction,success_percentage
0,gpt-3.5-turbo-0301,react-1_0,True,False,9045,92,117,2,16,4724,833,12,4724,10983102,92973,72,68.1481
1,gpt-3.5-turbo-1106,jsonstate-1_0-k-goal+current_location+current_inventory+thought+action,True,False,9045,79,97,38,0,2554,850,223,673,9276138,164437,24,58.5185
2,gpt-3.5-turbo-1106,jsonstate-1_0-k-thought+action,True,False,9045,85,110,25,0,2950,666,139,251,7870832,111550,98,62.9630
3,gpt-3.5-turbo-1106,react-1_0,True,False,9045,86,114,21,0,3775,1251,164,3775,8067788,96769,347,63.7037
4,gpt-3.5-turbo-1106,stringstate-1_0-k-action,True,False,9045,49,119,16,0,4564,2136,106,140,7849564,53916,232,36.2963
5,gpt-3.5-turbo-1106,stringstate-1_0-k-current_location+current_inventory+action,True,False,9045,70,119,16,0,3839,1449,152,236,8677049,90512,44,51.8519
6,gpt-3.5-turbo-1106,stringstate-1_0-k-current_location+current_inventory+thought+action,True,False,9045,100,124,11,0,2712,555,74,269,7635450,114354,72,74.0741
7,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+action,True,False,9045,69,119,15,1,3888,1657,106,111,8445917,95651,46,51.1111
8,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+current_location+current_inventory+action,True,False,9045,87,119,16,0,3207,966,153,166,8238726,106408,26,64.4444
9,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,True,False,9045,104,125,10,0,2580,521,54,256,8172650,132108,81,77.0370
10,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+thought+action,True,False,9045,87,120,15,0,3192,803,100,132,9023788,124383,182,64.4444
11,gpt-3.5-turbo-1106,stringstate-1_0-k-thought+action,True,False,9045,91,114,21,0,2829,700,111,157,6712367,89187,133,67.4074

In [290]:
file_name = "v4_1_2_eval_resample"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,success_percentage
0,gpt-3.5-turbo-1106,react-1_0,False,True,9045,60,133,2,0,5834,44.4444
1,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,False,True,9045,66,135,0,0,4453,48.8889

In [291]:
file_name = "v4_1_2_eval_resample_correction"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,success_percentage
0,gpt-3.5-turbo-1106,react-1_0,True,True,9045,89,132,3,0,4610,65.9259

In [292]:
file_name = "v4_1_2_eval_correction_resample"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,success_percentage
0,gpt-3.5-turbo-1106,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,True,True,9045,103,134,1,0,2868,76.2963

In [18]:
file_name = "v4_1_3_eval"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,num_nothing_happens,num_repetitions,num_no_command,total_in_token_accumulated,total_out_token_accumulated,num_correction,success_percentage
0,gpt-3.5-turbo-0125,react-1_0,False,False,9045,46,121,14,0,6608,2101,102,6607,15812025,104203,0,34.0741
1,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+current_location+current_inventory+action,False,False,9045,75,117,18,0,3439,1198,135,379,9051630,111200,0,55.5556
2,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,False,False,9045,76,128,7,0,3704,986,42,270,12880600,198444,0,56.2963

In [19]:
file_name = "v4_1_3_eval_correction"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,num_nothing_happens,num_repetitions,num_no_command,total_in_token_accumulated,total_out_token_accumulated,num_correction,success_percentage
0,gpt-3.5-turbo-0125,react-1_0,True,False,9045,94,124,11,0,4164,954,109,4163,9411421,67994,202,69.6296
1,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+current_location+current_inventory+action,True,False,9045,71,111,24,0,3210,1128,145,394,8263853,103748,12,52.5926
2,gpt-3.5-turbo-0125,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,True,False,9045,102,128,7,0,2615,454,36,198,8434848,132382,42,75.5556

In [9]:
file_name = "v4_1_5_eval_correction"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,num_nothing_happens,num_repetitions,num_no_command,total_in_token_accumulated,total_out_token_accumulated,num_correction,success_percentage
0,gpt-3.5-turbo-instruct,react-1_0,True,False,9045,73,127,3,5,6075,1685,22,6075,14222428,169087,131,54.0741
1,gpt-3.5-turbo-instruct,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,True,False,9045,86,86,14,35,2338,362,70,88,6540229,188025,10,63.7037

In [11]:
file_name = "v4_1_5_eval"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,num_nothing_happens,num_repetitions,num_no_command,total_in_token_accumulated,total_out_token_accumulated,num_correction,success_percentage
0,gpt-3.5-turbo-instruct,react-1_0,False,False,9045,68,122,8,5,6362,1799,38,6360,15011107,152069,0,50.3704

In [58]:
file_name = "v4_1_7_eval_correction"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,num_nothing_happens,num_repetitions,num_no_command,total_in_token_accumulated,total_out_token_accumulated,num_correction,success_percentage
0,gpt-4o-mini,react-1_0,True,False,9045,92,118,17,0,4919,743,172,4918,12524588,120381,153,68.1481
1,gpt-4o-mini,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,True,False,9045,97,132,3,0,3208,539,32,30,11642707,221792,129,71.8519
2,meta/llama-3.1-8b-instruct,react-1_0,True,False,9045,0,0,135,0,1290,1024,765,1290,2165338,33977,0,0.0000
3,meta/llama-3.1-8b-instruct,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,True,False,9045,0,0,135,0,1500,1182,843,1217,3980583,83230,0,0.0000

In [61]:
file_name = "v4_1_9_eval_correction"
new_eval = load_data(file_name)
# new_eval.head()

x,y = analyse_data_new(new_eval)
y.to_csv(f"../results/{file_name}_scores.csv",sep="&",index=False, float_format='%.2f')
x.head()

,model,prompt_name,correction,resample,env_idx,success,done,early_stop,error,num_of_steps,num_nothing_happens,num_repetitions,num_no_command,total_in_token_accumulated,total_out_token_accumulated,num_correction,success_percentage
0,mistralai/mixtral-8x22b-instruct-v0.1,react-1_0,True,False,9045,98,101,34,0,3334,725,204,3334,6686912,62589,38,72.5926
1,mistralai/mixtral-8x22b-instruct-v0.1,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,True,False,11762,113,116,19,22,2146,389,119,261,5883290,105505,10,83.7037

In [48]:
create_pivot(new_eval)

env_type,model,prompt_name,clean,cool,examine,heat,put,puttwo
0,mistralai/mixtral-8x22b-instruct-v0.1,react-1_0,20,18,10,17,24,9
1,mistralai/mixtral-8x22b-instruct-v0.1,stringstate-1_0-k-goal+current_location+current_inventory+thought+action,9,9,5,10,12,2

In [76]:
new_eval.to_csv("../playgrounds/v4_scores.csv",sep=",",index=False)

In [617]:
deepdive2 = load_data("deepdive_results_v4.csv",collect_results=True, override_filepath=True)
deepdive2.head()

,total_nothing,total_not_valid_nothing,put_not_valid_nothing,hallucinated_not_valid_nothing,hallucinated_example,fake_not_h_not_valid_nothing,fake_command_example,total_valid_nothing,take_valid_nothing,valid_nothing_example,...,num_json_dsnt_load,num_multi_json,num_no_json,num_json_and_text,error,early_stop,keys_removed,additional_prompt_annotation,trace_file,prompt_file
0,0,0,0,0,NO_EXAMPLE,0,NO EXAMPLE,0,0,NO EXAMPLE,...,9,0,9,0,1,1,react-2-swaped,NaN,game_logs/alfworld_eval_v2_1_eval_0-135/OpenAI...,game_logs/alfworld_eval_v2_1_eval_0-135/prompt...
1,0,0,0,0,NO_EXAMPLE,0,NO EXAMPLE,0,0,NO EXAMPLE,...,14,0,14,0,1,1,react-2-swaped,NaN,game_logs/alfworld_eval_v2_1_eval_0-135/OpenAI...,game_logs/alfworld_eval_v2_1_eval_0-135/prompt...
2,0,0,0,0,NO_EXAMPLE,0,NO EXAMPLE,0,0,NO EXAMPLE,...,6,0,6,0,1,1,react-2-swaped,NaN,game_logs/alfworld_eval_v2_1_eval_0-135/OpenAI...,game_logs/alfworld_eval_v2_1_eval_0-135/prompt...
3,0,0,0,0,NO_EXAMPLE,0,NO EXAMPLE,0,0,NO EXAMPLE,...,6,0,6,0,1,1,react-2-swaped,NaN,game_logs/alfworld_eval_v2_1_eval_0-135/OpenAI...,game_logs/alfworld_eval_v2_1_eval_0-135/prompt...
4,24,4,3,0,NO_EXAMPLE,4,place cloth 2 in cabinet 4,20,4,clean handtowel 2 with spraybottle 1,...,50,0,50,0,1,1,react-2-swaped,NaN,game_logs/alfworld_eval_v2_1_eval_0-135/OpenAI...,game_logs/alfworld_eval_v2_1_eval_0-135/prompt...

In [619]:
x = analyse_deepdive(deepdive2)
x.head()

,model,keys_removed,total,success,done,num_of_steps,total_nothing,total_not_valid_nothing,hallucinated_not_valid_nothing,fake_not_h_not_valid_nothing,put_not_valid_nothing,total_valid_nothing,take_valid_nothing,normalised_nothing,normalised_not_valid_nothing,proportion_of_not_valid_in_nothing,proportion_of_valid_in_nothing,proportion_of_hallucinated_in_not_valid,proportion_of_fake_in_not_valid
0,gpt-3.5-turbo-0125,react-2-swaped,135,86,111,3028,928,619,297,322,215,309,172,0.306473,0.204425,0.667026,0.332974,0.479806,0.520194